### ISSUE TITLE
What happens when there is 50:50 ratio in consensus voting mechanism considering the fact that we are going with odd number of nodes and provided that one nodes goes off-line before submitting their response

### ISSUE THREAD

**Issue by UAvinash7** [lni/dragonboat#108]
Hi @lni
I was exploring dragonboat multigroup libraries set and came across an interesting question which is: I've a leader node and 4 follower nodes where leader is proposing a transaction as valid (i.e. true) where as follower node F1 also proposing the transaction as valid, but follower nodes F3 and F4 are proposing the transaction as invalid (i.e. false) and during the same time the follower node F2 goes offline (the reason can be anything, either malicious behavior or due to some hardware/power issue). So, in this case, what is the fate of the proposed transaction i.e. whether it will be accepted and appended to the ledger or it will get rejected as the voting ratio is 50:50 and also suggest how this situation can be overcomed.
Hoping for a reply
Thanks in advance!

**Comment by motecshine** [comment]
In 'raft paper', all events will be handled by the leader (strong leader).

**Comment by lni** [comment]
In raft, nodes in a raft cluster do not vote on proposals, thus there won't be such 50:50 split vote.

**Comment by UAvinash7** [comment]
Hi lni,
Thanks for prompt response!
Now need one more clarification from you:
Consider a RAFT Cluster with 5 nodes (1 Leader and 4 Followers). Here, there is a clear chance that two followers may vote for a proposed transaction as yes and the remaining two followers may vote as no. How do you handle this tie in dragonboat?
Awaiting your response!
Thanks in advance!

**Comment by lni** [comment]
@UAvinash7 as explained above, nodes do not vote for proposals in Raft. If you want to know what happens when two followers *propose* certain value while two other followers *propose* something different at the same time, for such case, all proposals will be passed to the leader first and then got processed like all other regular proposals - nothing is really special here. 

I'd recommend you to read the raft paper first, it will give you a clear idea on what raft can/can not do for you.
