### ISSUE TITLE
Use Pebble as the default LogDB storage engine

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#122]
Switch to pebble as the default LogDB storage engine. 

Existing users using RocksDB as the LogDB storage engine will be able to transparently migrate to pebble as pebble provides bidirectional compatibility with RocksDB.

**Comment by tephrocactus** [comment]
Why not just use simple custom kv store implementation like the following one?

1. Use separate directory for raft log files;
2. Directory contains file with latest raft log index which is updated every time new entry is written; 
3. Each log entry goes in a separate file. Name of a file is it's index;
4. Use in-memory b-tree to manage entry files (ordering, range scans, e.t.c). B-tree element is just a uint64;
5. On process restart - list files in a log directory and recreate b-tree using file names.
6. "Compaction" of log entries is nothing more than removing files from disk and removing elements from a b-tree. 

Such an implementation has the only external dependency - some b-tree library. It's performance comparable with rocksdb based one and memory/disk consumption is much lower. It will not introduce additional write amplification since there is no background merges. Contention is also not the issue because main sync-target is a b-tree and index file which are updated very quickly. And it's just about 500 lines of code.

I'm using thing like this to implement replication log for traditional replication model. It looks like raft log has the same properties.

My point is just that using full-featured kv store like pebble or rocksdb is an overkill for dragonboat's use case. It adds complexity and demands more resources. Maybe I'm wrong since I'm new to dragonboat.

**Comment by lni** [comment]
@tephrocactus thanks for sharing the idea. 

The main issue with the approach you described above is the extra synchronization (fsync()) costs required when there are large number of active raft clusters. For posix systems like Linux, the above approach will take two fsync() calls per raft log entry, one for the file itself and one for the parent directory. When there are large number of active raft clusters keep getting proposals, the number of fsync() calls per unit time will be a problem as fsync() is pretty expensive. 

I agree that using a KV store like RocksDB/Pebble to store raft log is not ideal. There were some discussions in the issues section and that is actually also the reason why the internal KV interface is never publicly exposed to allow users to adopt other KV stores - because I feel that KV store is not the ideal choice. 

That being said, it is an okay choice. When used for a raft log store with very low typical read:write ratio, read amplification is not a very big concern here, if (a big IF) users can issue compactions (each is just a single tombstone record written to the DB) to clean out no longer required log entries in a timely manner then the write amplification can also be well managed. LSM-tree based KV stores are thus not that bad when used with care. That is probably also the reason why both TiDB and CockroachDB use LSM-tree based KV stores to store their raft log as well.

**Comment by lni** [comment]
v3.3 uses pebble by default.
