### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by tephrocactus** [lni/dragonboat#136]
### Dragonboat version
`3.2.2` and `3.2.3`

### Expected behavior

Application build on Linux with `github.com/lni/dragonboat/v3 v3.2.2` in `go.mod` must be successful.

### Actual behavior

Build fails with error:

```
vendor/github.com/lni/dragonboat/v3/internal/vfs/vfs.go:42:5: cannot use &PebbleFS literal (type *PebbleFS) as type "github.com/cockroachdb/pebble/vfs".FS in assignment:
        *PebbleFS does not implement "github.com/cockroachdb/pebble/vfs".FS (missing GetFreeSpace method)

vendor/github.com/lni/dragonboat/v3/internal/vfs/vfs.go:51:9: cannot use &PebbleFS literal (type *PebbleFS) as type "github.com/cockroachdb/pebble/vfs".FS in return argument:
        *PebbleFS does not implement "github.com/cockroachdb/pebble/vfs".FS (missing GetFreeSpace method)
```

Also tag for dragonboat `v3.2.3` has typo: `v.3.2.3` . This version does not fetch automatically by `go mod tidy`.

### Steps to reproduce the behavior

1. `import "github.com/lni/dragonboat/v3"` and use lib somewhere in application code;
2. run `go mod tidy`;
3. run `go mod vendor`;
4. build application with or without `-tags="dragonboat_no_rocksdb"`

**Comment by tephrocactus** [comment]
Removing `github.com/cockroachdb/pebble` from `go.mod`, which was marked as //indirect, and then retrying `go mod tidy` & `go mod vendor` helped. Maybe not a dragonboat issue.

**Comment by lni** [comment]
The typo in tag has been fixed. Thanks for reporting! 

That pebble related build issue is more tricky - 

Basically, dragonboat has an implementation of the "github.com/cockroachdb/pebble/vfs".FS interface based on an old but more stable version of pebble. You have a more recent version of pebble introduced into your build and that pebble version has a new method added to its "github.com/cockroachdb/pebble/vfs".FS interface. Dragonboat's implementation of that vfs.FS interface became incomplete in your build and the compiler complained about that. 

If you just got a more recent version of pebble introduced into your build by mistake, which sounds like the case to me based on your reply above, then it is not a real issue. 

It becomes a real issue when your project actually uses a more recent version of pebble somewhere else in its dependency graph. In that case, a correct approach requires pebble's maintainers to create a new module version (say github.com/cockroachdb/pebble/v2) whenever a public interface ("github.com/cockroachdb/pebble/vfs".FS here) has a new method added (GetFreeSpace() here). It is a bit tricky because pebble is still marked as v0 being actively developed, its API is not considered as finalized, such changes to its public interface under the same module version (which is none) is probably considered as okay. I have the feeling that pebble will follow golang's module version conventions once it moves out of v0.
