### ISSUE TITLE
NodeHost Address Changes

### ISSUE THREAD

**Issue by jkassis** [lni/dragonboat#140]
When a StatefulSet pod goes down in kubernetes, it comes back up with a different IP address. Thus when bringing up a failed / downed NodeHost it will have a different IP. But it will retain the previous RAFT state since that state it is stored on a PersistentVolume.

Is there a way to update ADDRs for Nodes that have joined existing clusters?

P.S. FWIW It seems a bit strange to me that Nodes are registered with their IP addrs... lots of duplicate data. Perhaps they should be registered against NodeHost ids? Then only one update is required to change the NodeHost IP.

Thanks in advance!

**Comment by lni** [comment]
You don't have to use IP addresses, surely you can use DNS names. For a DNS name like host01.example.com, what is the difference between host01.example.com and an ID such as 0e46ab3e681f? 

Also note that in the current code, the only assumption made is that when a Raft node is introduced to the system, a string type static identifier consistent with its NodeHost.RaftAddress() must be provided. Users can extend the transport layer without touching the raft/rsm/storage layers to implement whatever ID/addressing schemes they like, the only change to the existing code is to remove some regex checks.

**Comment by jkassis** [comment]
ok. good i can extend the transport. i was in mobile gaming for many years. big MMOs. using DNS isn't safe because it makes the DNS server an extra point of failure. plus it adds latency. all the professional ops people said no way, plus we did many benchmarks that crushed K8s DNS. you can cache DNS responses, but now you have a cache synchronization problem. it's very awkward, in particular, with K8S StatefulSets because the DNS isn't configured until the pod passes a liveness check, which it conceptually should *not* pass (if it is a raft node) until it is added to the raft. Catch 22.

**Comment by lni** [comment]
So we need a mapping system to map IDs to IP addresses so nodes can eventually talk to each other using those dynamically assigned IP addresses.  

To address your concerns above, such a mapping system must be (1) fully decentralized, no single point of failure, (2) present to its users as a single entity with good consistency, (3) high performance. More strictly, one might also expect that (4) member nodes used to form such mapping system don't have fixed IP addresses and (5) no DNS.

Will be delighted to see how such a system can be built within reasonable efforts as a component for a consensus library. Just for the item (2) above, you probably need a consensus library!  ;)

**Comment by gedw99** [comment]
Sounds like you need an external discovery server like etc for consul

**Comment by lni** [comment]
A gossip service based approach has been added to allow NodeHost.RaftAddress to change after each restart. 

You can set NodeHostConfig.AddressByNodeHostID to enable it. Once enabled, all those target parameters used in NodeHost's APIs (such as StartCluster, RequestAddNode etc.) need to be NodeHostID values. Basically, rather than saying "I want my cluster 2 node 3 to be running on the NodeHost instance running at mydomain.com:1234", you'd be requesting "I'd like to have my cluster 2 node 3 to be running on the NodeHost instance identified by NodeHostID nhid-xxxxxxxxxxxxxx".

TestGossip in nodehost_test.go is an example on how to use it. 

I haven't deployed it in my own systems yet, will probably start using it in March.
