### ISSUE TITLE
to pebbledb or not to pebbledb

### ISSUE THREAD

**Issue by jkassis** [lni/dragonboat#144]
pebbledb is now the default, yet the logs warn...

`pebble support is experimental, DO NOT USE IN PRODUCTION`

i think the docs also mention that the *squeemish* should go for rocksdb.

where exactly does pebbledb stand wrt dragonboat today?

**Comment by lni** [comment]
Pebble is the default storage engine for Raft Log in the master branch, which is the development branch of Dragonboat. Pebble will be marked as production ready once v3.3 is released, before that it should be considered as beta (in development). 

Please note that there is no known issue for the Pebble support, v3.3 is not released yet because I'd like to wait a little bit longer to allow more pebble bugs to be exposed in CochroachDB which is the owner and main user of pebble.

**Comment by jkassis** [comment]
thanks @lni ... one more question... is there a way to control memory usage of pebble through dragonboat? if not... we might consider making this a feature request.

**Comment by lni** [comment]
@jkassis could you please open a new issue on the memory usage issue so other users can easily search and find the discussions in the future? will be happy to help you on that.
