### ISSUE TITLE
NodeID

### ISSUE THREAD

**Issue by sethyates** [lni/dragonboat#153]
What is the recommended method for assigning NodeID? If we use a deterministic method, and a node is removed, then it cannot be added back with the same NodeID (`rej exist` error in log). Our nodes are managed using Kubernetes and Helm, which doesn't provide much mechanism for manually assigning NodeID's.

**Comment by lni** [comment]
You are free to choose any NodeID you like. NodeID is just a numeric value picked by your code, I don't think it has anything to do with software like Kubernetes. 

Note that in the context of raft/dragonboat, removing a node means using membership change operation to permanently remove a node from the raft cluster. If you have a crashed node that can be restarted, that node is not "removed" when it is offline. 

Not allowing removed NodeID to be reused by a new Node is not a restriction introduced by Dragonboat, it is a fundamental safety requirement of the Raft protocol. Imagining that you have a node with ID 100 and let's say that node has all entries up to index 200, if you remove that node and then add another new node with the same ID 100, that will confuse all other nodes in the same Raft as node with ID 100 previously confirmed to the cluster that it has all entries up to index 200, they are now all gone on the new node with the same ID 100.

**Comment by sethyates** [comment]
Thanks!

**Comment by uber42** [comment]
Now I am trying to set up automatic deployment of the cluster and I need to somehow automatically set the identifier for the nodes

So far identifiers are set when adding each node manually, but due to the fact that some node could be removed, it may turn out that the specified identifier of the node may already exist in the cluster, then to the addition will be completed with an error

There is an idea to increment the identifier at the level of the cluster logic and not set it manually, but in order for such logic to be consistent and the identifiers do not intersect, a quorum condition is necessary, which is undesirable when changing the composition of the cluster, are there any ways to achieve automatic assignment of cluster identifiers?
