### ISSUE TITLE
Factory for IKVStore

### ISSUE THREAD

**Issue by stffabi** [lni/dragonboat#155]
Would it be possible to introduce an additional factory on the config for injecting custom `IKVStore` implementations?

This would make it possible to use other KV Stores without having to fully implement the `ILogDB` and would make it a lot more easier to write a plugin for another KV Store.

Thank you very much for this awesome project.

**Comment by lni** [comment]
I am afraid that providing public access to the IKVStore interface only makes it much easier to implement a broken plugin that will eventually have data loss or corruption. For all open source Go KV stores that I am aware of, Pebble is the only one that can tick all boxes.

Another reason why it is not made publicly accessible is because KV store is not the ideal solution for storing raft logs.

**Comment by stffabi** [comment]
Thanks for your reply.I understand your second point. We were just interested in using Badger as we are using it for other projects. I'm aware of your concerns about it, but we can life with its limitations.

**Comment by lni** [comment]
Badger support was added back in Jan 2019, but later removed due to the concern of its reliability & lack of some essential features such as range delete.
