### ISSUE TITLE
PreVote Support

### ISSUE THREAD

**Issue by SergeyLysanov** [lni/dragonboat#165]
Found in code the following comment:
`// Features currently being worked on -
//  * pre-vote
//`

Any plans to support pre-vote phase in near future?
Thanks!

**Comment by lni** [comment]
One way or another it will eventually be supported, but I think it is currently low on my priority list. If someone wants to give it a go and contribute PR for this feature, I'd be happy to help.

**Comment by lni** [comment]
Some extra info on this topic for those who are interested - 

Pre-vote is primarily useful for the situation when a node is partitioned away from other nodes, e.g. when the node can send messages to the leader but couldn't receive messages from the leader. Without pre-vote, the partitioned node's term value will keep increasing. In a basic raft implementation, such partitioned node will keep sending out RequestVote messages with higher term values to repeatedly force the leader node to step down. This issue is extremely disruptive and has to be addressed in a raft implementation. Pre-vote is one way to resolve this issue, but it is not the essential solution. 

When check leader quorum is enabled, which is the true by default in Dragonboat, such RequestVote messages should be dropped when the leader is up and running with confirmed quorum. Dragonboat already does that, so the above described issue doesn't really affect Dragonboat. 

What Pre-vote can really help for Dragonboat is that it avoids the once off election per network partition event. When the above mentioned partitioned node regain its full connectivity with the leader node, it will send response messages with higher term. That will force the leader to step down for a new election only once per network partition event. Such extra election can be avoided by having the pre-vote feature.  

Now the question is how often will you see such network partition events and what is the actual impact for that one extra election per network partition event. 

My understanding is that such network partition events are not very often and the impact of each election is not that significant. It will be useful to have pre-vote, but the increased robustness is pretty small and that is the reason why pre-vote is low on the priority list.

**Comment by lni** [comment]
pre-vote support has been added.
