### ISSUE TITLE
Propose does not return all results

### ISSUE THREAD

**Issue by lebovski** [lni/dragonboat#166]
Hi I need help understanding how SyncPropose works.

Suppose I have a Raft cluster and I send SyncPropose from the leader, one of the nodes (not leader) gives an error, which is stored in the result (sm.Result). I expect Propose to return me a set of sm.Result from all nodes, but it only returns the result from the leader.
Is it possible to get all the results? Or how can I validate the result of Propose?

### Dragonboat version
3.3.0 (Rel)

**Comment by lni** [comment]
I'd like to reiterate the definition of error in this context - 

For unexpected failures, e.g. disk is full or corrupted, the Update method should return a non-nil error and this will cause the program to panic. You can then resolve the underlying issue and restart your program, the proposal that led to such non-nil error is guaranteed to be re-applied after restart. This kind of failure is usually isolated to certain node, e.g. only one of your node has disk related error, other nodes are fine. 

For expected failures, e.g. a proposal to update the Replicated State Machine (RSM) can't be applied to update the RSM state due to some internal logic restrictions, the proposal is considered as rejected, the Update method should return nil for error and sm.Result should contain required info for your client to be notified for such rejection. In other word, it is not really an error, it is just another applied proposal. This kind of failure should happen on all nodes of the same Raft cluster.  As mentioned in the godoc of the Update method - 

```
// The Update method must be deterministic, meaning given the same initial
// state of IStateMachine and the same input, it should always reach to the
// same updated state and outputs the same returned value.
```

For what you described, please check to see why your nodes are behaving differently, do they have the same initial state before the proposal is applied? Do they rely on some external data sources (clock, local file, input from remote machine etc)? The bottom line is when your IStateMachine/IOnDiskStateMachine is correctly implemented, all your nodes from the same Raft cluster should return the same value for the same proposal, you thus don't need the sm.Result from remote nodes.

**Comment by rajeshkgit** [comment]
@lni #164 I was also looking for a way to propagate the results from all the Raft nodes, instead of its being returned from the leader state machine. 
**_IStateMachine/IOnDiskStateMachine is correctly implemented, all your nodes from the same Raft cluster should return the same value for the same proposal"_**
This may not work in the case where your StateMachines are making use of an external database or external data source for persisting the application state (It's not a centralized data store, each Raft node interacting with its own instance of a data store). A typical failure scenario could be not able to connect to the database on a few of the raft nodes due to localized issues, in this case, it would be helpful to have a mechanism to propagate the individual results to the leader and leader decides on the proposal outcome based on the whether the proposal being accepted by the quorum or not.

**Comment by lni** [comment]
@rajeshkgit when dragonboat requires all nodes from the same raft cluster to return the same results when given the same proposal to apply, that is not a constrain introduced by dragonboat, it is a fundamental requirement of the Replicated State Machine model. Both Raft and Paxos are built on top of this fundamental model.

As explained above, when impacted by the connectivity issue in your mentioned example, that affects just some nodes in the raft cluster, it is actually a perfect example of the "unexpected failure" I mentioned. The program should return a non-nil error so dragonboat will panic. This allows you to resolve the underlying "localized issue" without impacting the availability of the raft cluster so the replica node can continue later. 

Also note that you want mechanisms to "propagate the individual results to the leader and leader decides on the proposal outcome based on the whether the proposal being accepted by the quorum or not", that is not what a consensus library suppose to do.

**Comment by lni** [comment]
also note that client can make proposals on any nodes, not just the leader node, the returned result is generated by the local node which can be a follower node.
