### ISSUE TITLE
Respond after processing all the nodes.

### ISSUE THREAD

**Issue by lebovski** [lni/dragonboat#167]
Is it possible to configure the dragonboat so that the Propose only responds after processing all the nodes?

If I understand everything correctly, now Proposer processes the replies from the quorum and releases the client.

**Comment by lni** [comment]
If I understand correctly, you want the client to be notified only when the proposed command has been applied to all replica nodes. Dragonboat doesn't have such feature and I am not sure how such a feature can be useful & practical for a consensus library. 

For example, for a 3 nodes raft cluster, let's say node A and B are up and running when the third node C is unreachable due to network partition. Your client can successfully have proposals committed and applied in this raft cluster, but as the proposals won't be able to reach node C, your client won't be notified at all for those successfully committed and applied proposals in your described approach above. 

Note that your application does have full control on the Update() method, e.g. although not recommended, you can have code inside your Update() method to notify some remote processes when you think it is necessary.

**Comment by lebovski** [comment]
Yes, that's right, thanks for the answer.
