### ISSUE TITLE
Can I just compact log without snapshot ?

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [lni/dragonboat#24]
Can I just compact log without snapshot  , how ?
Cause, I use levelDB for kv statemachine ,not mem kv store like btree , no snapshot needed .
And ,In the case of large concurrent reads and writes, does snapshot affect system performance?

**Comment by lni** [comment]
Snapshot is not just for the node itself to restart. It is also used by the leader to help slow followers to catch up. In your question and described approach, when some raft logs are compacted (removed) but not included in any snapshot, it means all such update info included in those compacted entries is gone, slow followers or followers joined after the compaction won't get updated from those entries.  

Your leveldb based statemachine should be partitioned into multiple Raft groups, say each covering certain key range, each range will be handled by a raft group. That is why you need a multigroup raft library like Dragonboat. Those raft groups are going to take snapshots hopefully at different time, and because they are partitioned into small key ranges, they should be able to complete the snapshotting much faster. 

Note that, how to partition your leveldb across multiple raft groups, how to further split/merge them will be handled and implemented by your design/application. Dragonboat provides the infrastructure to allow your application to have large number of such Raft groups and make sure they work efficiently.

**Comment by zhengxiaochuan-3** [comment]
ok , got it .
thanks .

**Comment by SunRunAway** [comment]
The additional snapshot file in this case is not necessary. To help slow followers to catch up, can we take a snapshot from the leveldb kv statemachine temporarily and transfer it to slow followers streamly.

**Comment by lni** [comment]
@SunRunAway what you described is basically taking snapshots for disk-based state machine, as described in the raft thesis. 

Dragonboat doesn't has that supported in the current version. The only challenge here is how to implement it in a way that entry-level users won't get confused. 

Can't promise anything, but with pretty good chance that it will be the next major feature added to Dragonboat.

**Comment by zhengxiaochuan-3** [comment]
very excited to this feature @lni @SunRunAway

**Comment by brk0v** [comment]
One way how this could be done would be saving in a snapshot only committed version of the underlying storage without any actual data. And then for bootstrapping new nodes and catching up you should transfer this snapshot and using a side channel download database from the leader up to that version. MVCC and snapshot capabilities of your storage are supposed to help here.

**Comment by zhengxiaochuan-3** [comment]
@brk0v  Good idea , my storage is goleveldb  .
https://godoc.org/github.com/syndtr/goleveldb/leveldb#Snapshot

so, It can be done !
