### ISSUE TITLE
StateMachine Update in real world

### ISSUE THREAD

**Issue by gensmusic** [lni/dragonboat#31]
```
type IStateMachine interface {
  Update(data []byte)  uint64
}
```
in a real world, we cann't assume Update() always have the same result. If one of node failed to `Update`, lastApplied is still updated. How can we avoid this ?

**Comment by lni** [comment]
> we cann't assume Update() always have the same result

No, when using consensus algorithms, a big requirement (not assumption) is that Replicated State Machines backed by the consensus algorithm are deterministic. With the same initial state and the same input (the data []byte input here), calling Update() on all your replicas should lead to the same output and the same new state. 

> If one of node failed to `Update`, lastApplied is still updated.

Please define what do you mean by "failed to update". 

When one of the nodes failed to "Update" because the input is considered as invalid, while other nodes all successfully complete the Update as they see the input as valid, then you have a bad design for your state machine. See the explanation above. 

When one of the nodes failed to Update because the disk is faulty or run out of memory, then you must panic inside the Update method. The lastApplied value is not persisted. Once the issue is resolved, you can restart the Raft node and the same log entry will be executed again using the Update() method.

When some requests can not be fulfilled by design, that is not a failure. Say when all your State Machines show that variable X maintained by your State Machine has a value of 1,  but Update() wants to run an update command "X=2 if X==3", obviously it is not a failure, all your State Machines should return a uint64 code to indicate such outcome.

**Comment by gensmusic** [comment]
by `failed to update` i mean disk faulty. Your answer is quite clear to me.
Thanks a lot.
