### ISSUE TITLE
How can we know if the quorum is lost for a shard?

### ISSUE THREAD

**Issue by vidhikgupta** [lni/dragonboat#319]
So , I want to know the quorum is lost and client shouldn't sent requests to this cluster. Right now no method in NodeHost gives me that information.

**Comment by lni** [comment]
In distributed system, a fundamental problem is that there is no way to ***reliably*** tell that a node has definitely failed. This is not a missing feature in some random libraries, it is one of the most fundamental problem in computer science. Because of that, there is no way to tell reliably whether your quorum is lost.

You can implement whatever method you feel comfortable to detect ***potential*** lost of quorum, but that is just an "educated guess" at best. There shouldn't be such "feature" in dragonboat as it will mislead people who want their application to rely on the correctness of such "detection". 

If your application just want an "educated guess", just make say 3 proposals with reasonable timeout values, you can make them from different replicas. If they all timeout, you know the quorum is very likely to be lost. Again - this is just a guess.
