### ISSUE TITLE
How to reduce disk space usage?

### ISSUE THREAD

**Issue by luluz66** [lni/dragonboat#372]
This is the config we use: 
```
rc := dbConfig.Config{
		ReplicaID:           replicaID,
		ShardID:             rangeID,
		WaitReady:           true,
		PreVote:             true,
		ElectionRTT:         20,
		HeartbeatRTT:        2,
		CheckQuorum:         true,
		SnapshotEntries:     1000000,
		CompactionOverhead:  1000,
		OrderedConfigChange: true,
	}
```

We noticed after load testing for a while (with 1KB entries) that Raft is using 365 GiB disk space for one server. The sharded logdb files are ~20GB each. We are going to try enabling snappy compression for snapshots and entries, but are there any other guidelines for tweaking the config to reduce disk size?

**Comment by lni** [comment]
internally, there are 16 sharded logdb by default. so ~20 x 16 = 320GB seems to be close to the total of 360GB you saw. 

if you are using pebble based log storage, which is the default one, you may see such high disk usage before pebble compaction is issued to the underlying log storage. Would you like to try NodeHost.RequestCompaction() to see whether that can help.

**Comment by lni** [comment]
also a little bit extra background info - 

when you write more and more stuff into pebble overtime, assuming dragonboat snapshotting is working as expected, pebble will eventually use compaction to reclaim those disk spaces automatically for you. there are lots of knobs to tune here, they are defined in LogDBConfig, please have a look including its related underlying code, you probably need some decent understandings on how leveldb/rocksdb/pebble works to be able to tune those parameters successfully. 

you may also want to try the new log storage engine called tan, which avoids all these problems by design and provides better write throughput. its code can be found in internal/tan.

**Comment by luluz66** [comment]
I think the issue for us is the number of SnapshotEntries was set too high and we are not creating snapshot frequent enough.

**Comment by lni** [comment]
just FYI, if you are using on disk state machine, the total overhead to generate a snapshot is pretty small, as it just involves saving the tiny metadata of your state machine.
