### ISSUE TITLE
Add API to request a new snapshot to be created

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#49]
Add API to request a new snapshot to be created, its usage should be similar to the one used for requesting raft membership change.

**Comment by xianglinghui** [comment]
Hi, I may need this feature. 

I am developing a distributed storage，it should support auto-scaling.  An existed node may split to two node，the new node will begin running with an unempty stagemachine. I need let the new node to generate a snapshot when a new member join its cluster，because the new member need synchronize data.

**Comment by lni** [comment]
@xianglinghui 

this feature has been implemented in the coming released.

**Comment by xianglinghui** [comment]
It's wonderful.

**Comment by lni** [comment]
@xianglinghui 

This feature can now be previewed in the v3.0 beta release. It is implemented as a new NodeHost API named RequestSnapshot().
 
https://github.com/lni/dragonboat/tree/beta-release-3.0

nodehost_test.go contains some tests that can be used as examples on how to use this new API.

**Comment by lni** [comment]
in master branch, ready to be released.
