### ISSUE TITLE
Improvements for Local Reads

### ISSUE THREAD

**Issue by 256dpi** [lni/dragonboat#64]
To query a local node today one needs to call two methods to obtain the data:

```go
rs, _ := node.ReadIndex(clusterID, 10 * time.Second)
rr := <-rs.CompletedC
encodedData, _ := node.ReadLocalNode(rs, encodedQuery)
```

There are a couple of improvements I would like to discuss:

It seems to me that there is no way to call `ReadLocalNode` without ever calling `ReadIndex` first. Wouldn't it make sense to allow applications to read from the local node without linearizability guarantees?

I would suggest to provide a method signature that more reflects the eventual usage e.g. `ReadLocal(query []byte, linear bool) ([]byte, error)`. The methods can be split up if it makes sense that other computation is done between the two calls.

Since `ReadLocal` would always read from the local node and never query a machine over the network the encoding of the query seems unnecessary. Would it be possible to change the signature to something like `ReadLocal(query interface{}, linear bool) (interface{}, error)` (applying the previous change as well)?

With these changes the performance could be increased significantly in scenarios where local data is read with and without the need for linearizability. The later could potentially also be implemented today by accessing the underlying state machine directly. However, I think dragonboat should provide an interface for this, as it will allow manage the requested in the future to prevent collisions or other issues.

**Comment by lni** [comment]
@256dpi 

A custom factory function with one of the following signatures is passed into the StartCluster method when starting the node - 

func(uint64, uint64) sm.IStateMachine
func(uint64, uint64) sm.IOnDiskStateMachine

The returned sm.IStateMachine and sm.IOnDiskStateMachine instances are created by user code, users thus have full access to them. They can keep a reference to those instance and call its Lookup method directly to achieve what you described above - direct local read without linearizability guarantee. 

I am trying to make sure that NodeHost's interface is dedicated to one thing and one thing only - provide linearizable access to user data. When people choose to use NodeHost but don't want linearizability in certain valid use cases, they can use the above mentioned approach by completely bypassing the NodeHost interface. 

For your proposal to use interface{} as both the input and output of the local read method, I am leaning towards to do it, will get back to you soon. 

btw, thanks for all the inputs, more suggestions wanted! ;)

**Comment by 256dpi** [comment]
I think it makes sense for this library to only focus on linearizable access. However, the chosen approach to provide a factory for the state machine creates a mental conflict. It appears to one that the NodeHost is managing the instance and thus it might be gone without further notice. If it is only created once we might just pass in the already constructed state machine? That would also suggest that one can keep a reference to it and use it for fast non-linear reads. 

Thanks for considering the `interface{}` intput and output instead of `[]byte`. What do you think about combining the `ReadIndex` and `ReadLocalNode` methods?

> btw, thanks for all the inputs, more suggestions wanted! ;)

I'm happy to help, I think this project is on the way of becoming a really important building block for many projects. :-)

**Comment by lni** [comment]
There are good reasons to require the factory method to be passed in. For example, it allows further optimizations relate to how state machines are recovered from snapshots. So yes, in future releases, the factory method might be called multiple times for the same state machine.

I think I will definitely allow interface{} to be used as input/output of those read related methods. Using interface{} will cause extra allocations, I am fine with such extra allocations itself as long as there are other methods for performing similar read without requiring extra allocations, the problem is what is the best public APIs to provide.    

Please also note that there is already a method named SyncRead that performance a linearizable read in one method call.

**Comment by lni** [comment]
The signature of the Lookup method has been changed to 
```
Lookup(interface{}) (interface{}, error)
```

as I believe it is far more flexible for average cases. NodeHost APIs have been updated accordingly to accommodate the above change.    

An optional NALookup([]byte) ([]byte, error) can be implemented to retain the old interface/no extra heap allocation behaviour. NAReadLocalNode has been added to the NodeHost API to query local node using the optional NALookup method. NAReadLocalNode returns an statemachine.ErrNotImplemented when the optional NALookup is not implemented. 

Benchmark results comparing the updated Lookup method and the new NALookup method are provided below - 

```
BenchmarkLookup-12         20000000	        85.3 ns/op	      65 B/op	       3 allocs/op
BenchmarkNALookup-12    100000000	        19.9 ns/op	       0 B/op	       0 allocs/op
``` 

I've also added a new NodeHost API called StaleRead to allow direct read to the state machine without linearizability guarantee. As clearly indicated by its name, data returned by this new method should be regarded as stale read results.

**Comment by 256dpi** [comment]
Thanks for implementing the changes!

I can understand the motivation to also provide `NALookup` for performance reasons. But the benchmarks seem not to be 100% accurate. The `NoOP.Lookup()` function is allocating a slice while `NoOP.NALookup()` just returns the key. In real life bot would allocate some memory to return a result. If the lookup would be allocation free, it would not return any data and makes no sense anyway...?

Also, the `NALookup` would only be faster if the user would pass in a byte slice taken directly from the client and forward that to the state machine (to be truly allocation free). Again, in real life I'm 100% sure a requests (maybe a JSON body) gets decoded first then checked if it is valid and then forwarded. In that case, the new `Lookup` would always be more performant even with the allocation due to the usage of `interface{}`.

Based on that I would recommend to not add the `NALookup` method as it adds complexity without bringing much value.

**Comment by 256dpi** [comment]
I tried out the changes and got the following panic:

```go
// Lookup queries the state machine.
func (s *OnDiskStateMachine) Lookup(query interface{}) (interface{}, error) {
	if !s.opened {
		panic("Lookup called when not opened")
	}
	return s.sm.Lookup(query)
}
```

It's caused by `StaleRead` being executed while the state machine has not yet been opened. I think this should be legal and therefore the function should return an error instead of causing a panic.

**Comment by lni** [comment]
Micro benchmarks are never meant to be 100% accurate, it gives people a rough and quick idea on what is going on. In the provided benchmark results, even without the make([]byte, n) you mentioned, there are still 2 extra allocs/op caused by using interface{}. 

For NALookup, it doesn't need any allocation if the result is written into the input byte slice. The bottom line is users have full control of all allocations in such case. The same can not be said for the updated Lookup method. 

The JSON example you described is common but not generic. You are assuming that for _many_ applications the input is some kind of explicit Go struct instances unmarshaled from a []byte. It is common, that is why the default interface has been updated to accommodate that. That being said, it doesn't represent all use cases, e.g. my applications only use the NALookup interface. 

Please also note that NALookup is an optional method no one has to implement/look at. It only needs to be implemented when people does need to avoid those 2 unwanted allocs/op.

**Comment by lni** [comment]
For the panic issue, yes, an error should be returned in that case.

**Comment by 256dpi** [comment]
Thanks for fixing and the panic. I haven't considered reusing the input byte slice as the output. Seems to be a valid scenario for the additional `NALookup` interface. 👍
