### ISSUE TITLE
raftpb/raft_optimized.go的生成脚本是 - How raftpb/raft_optimized.go is generated

### ISSUE THREAD

**Issue by choleraehyq** [lni/dragonboat#93]
raft_optimized.go 是用 colfer 生成的吧，好像在 raftpb 里只有一个 pb 的生成脚本，好像没有 colfer 的生成脚本。

**Comment by lni** [comment]
The colfer definition used to generate the original raft_optimization.go only covers the Entry type. I made some modification to the generated code as well, e.g. added those SizeUpperLimit methods. From memory, those Messages/MessageBatch methods were modified from protobuf generated code. 

In short, the colfer definition file is not included because raft_optimized.go is not actually generated from it. 

I just sent you an email, please have a look.
