### ISSUE TITLE
Ondisk GetHash function  application?

### ISSUE THREAD

**Issue by xkeyideal** [lni/dragonboat#95]
See the docs `The hash should be generated in a deterministic manner which means nodes from the same Raft cluster are suppose to return the same hash result when they have the same Raft Log entries applied.`

See the example of ondisk, the GetHash function generate by all kvs md5.

if the GetHash return different value of nodes from the same Raft cluster, what will happened?

the example of ondisk, may ensure the value are all same?

thx

**Comment by lni** [comment]
Hi @xkeyideal, as mentioned in the doc, GetHash is optional so you don't need to implement it. 

It is currently not used/checked, so nothing really happens if different nodes of the same cluster return different hash values. In the future, we might use GetHash() to provide users the ability to check the consistency of their state machines. 

I will remove those GetHash methods from the examples soon.

**Comment by xkeyideal** [comment]
Thx for your answer
